name: Build SunamoClearScript

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoClearScript
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoClearScript/SunamoClearScript.csproj

    - name: Build
      run: dotnet build SunamoClearScript/SunamoClearScript.csproj --configuration Release --no-restore

  test:
    name: Test SunamoClearScript.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoClearScript.Tests/SunamoClearScript.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoClearScript.Tests/SunamoClearScript.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoClearScript.Tests/SunamoClearScript.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
